### ISSUE TITLE
Add admin features necessary for tracking logins and banning users

### ISSUE THREAD

**Issue by tec27** [ShieldBattery/ShieldBattery#168]
Desired features:
- [x] Track IP used to sign up for an account
- [x] Track unique IPs used to visit the site
- [x] Flag for whether or not a user is banned (can just be perma-bans for now, timed bans we can deal with later)
- [x] Permission to view IP/other user info and ban users
- [ ] Admin interface for viewing user info and searching other users that are related by  IP

Probably we should try to also track the last session ID associated with  an account/IP pair, so we can expire their sessions should a ban occur. And maybe provide some code that allows us to force a refresh from the websocket connection, in order to easily boot the user from all of our various service pieces.
