### ISSUE TITLE
Fix a few issues noticed after the release

### ISSUE THREAD

**Issue by 2Pacalypse-** [ShieldBattery/ShieldBattery#986]
```[tasklist]
### Tasks
- [ ] Chat service `init3` event should not include initial data as it can override the data received by the `chatReady` event (mainly affect the ordering of the channels). Instead upon joining a channel we should send channel info _after_ the `init3` event.
- [ ] Properly select the initial language in settings
- [ ] Fix the player search in the ladder page
```

**Comment by tec27** [comment]
I don't really agree with the first task, I think the data in `init3` is fine (it serves zero purpose if you don't include the data with it). The problem with `init3` currently is that you send it to clients when they connect, which should never be the case, it should only be sent directly after a channel is joined.

**Comment by 2Pacalypse-** [comment]
Yeah, I misspoke. That's what I _meant_ to write :)

**Comment by 2Pacalypse-** [comment]
Done in https://github.com/ShieldBattery/ShieldBattery/commit/49af0ad72af64b7ba6c9cd3044ed93a8da1a6ec2, https://github.com/ShieldBattery/ShieldBattery/commit/e1dce29df5fec700dbcc4369241d64ee86bb40a7, and https://github.com/ShieldBattery/ShieldBattery/commit/fdffb1e4a19d02a32d6312828fee9be10584a604
